# Generated by Django 2.2 on 2021-05-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('discount', models.FloatField(default=0)),
                ('expiration', models.DateTimeField(auto_now=True)),
                ('sketch', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('sales_volume', models.IntegerField(default=0)),
                ('pri_img', models.CharField(blank=True, max_length=255)),
                ('sec_img', models.CharField(blank=True, max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('color', models.IntegerField(choices=[(1, 'Black'), (2, 'Red'), (3, 'Blue'), (4, 'Green'), (5, 'Pink')], default=2)),
                ('size', models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], default=1)),
                ('flowerbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='Shop.Brand')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('rating', models.IntegerField(choices=[(1, 'bad'), (2, 'unwillingly'), (3, 'medium'), (4, 'good'), (5, 'perfect')], default=3)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Shop.Goods')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='User.User')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('goods_num', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, '未支付'), (2, '未送达'), (3, '未评价')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='User.User')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
