# Generated by Django 2.2 on 2021-05-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('snowID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=20)),
                ('is_active', models.IntegerField(default=0)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('station', models.IntegerField(choices=[(0, 'admin'), (1, 'staff'), (2, 'leader'), (3, 'boss')], default=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
